name: "edu_peak"
description: "Приложение для подтягивания знаний по школьным предметам"

publish_to: 'none'

version: 0.42.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  provider: ^6.1.1
  file_picker: ^10.3.0
  image_picker: ^1.0.4
  image_cropper: ^11.0.0
  path_provider: ^2.1.5
  http: ^1.1.0
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.0.0
  cookie_store: ^0.4.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.0.9
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/AppIcon.png